grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  persistence:
    enabled: true
    size: 10Gi
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
prometheus:
  prometheusSpec:
    replicas: 2
    retention: 15d
    retentionSize: 40GB
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: "2"
        memory: 6Gi
alertmanager:
  alertmanagerSpec:
    replicas: 2
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi
kube-state-metrics:
  metricLabelsAllowlist:
    - pods=[app.kubernetes.io/component,app.kubernetes.io/part-of]
prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
