apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexuschat-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nexuschat
  source:
    repoURL: https://github.com/Tuananh165-art/NexusChat.git
    targetRevision: main
    path: deployments/helm/nexuschat
    helm:
      releaseName: nexuschat
      valueFiles:
        - values.yaml
      parameters:
        - name: global.environment
          value: production
        - name: global.domain
          value: nexuschat.click
        - name: services.user.env.USER_AUTH_COOKIE_DOMAIN
          value: nexuschat.click
        - name: services.user.env.USER_OAUTH_COOKIE_DOMAIN
          value: nexuschat.click
        - name: services.uploader.env.UPLOADER_S3_PUBLICENDPOINT
          value: https://assets.nexuschat.click
        - name: imageDefaults.tag
          value: 2089bd96d17be713f6ee7ea572bbde6df2f620b9
  destination:
    server: https://kubernetes.default.svc
    namespace: nexuschat-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
