global:
  name: consul
  datacenter: dc1
  image: hashicorp/consul:1.19.1
  tls:
    enabled: true
  acls:
    manageSystemACLs: true
server:
  replicas: 3
  bootstrapExpect: 3
  storage: 20Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
connectInject:
  enabled: true
  default: false
  transparentProxy:
    defaultEnabled: true
controller:
  enabled: true
ui:
  enabled: true
  service:
    type: ClusterIP
prometheus:
  enabled: true
