{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nexuschat-default
  labels:
    {{- include "nexuschat.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8081
        - protocol: TCP
          port: 4000
        - protocol: TCP
          port: 8090
        - protocol: TCP
          port: 5005
        - protocol: TCP
          port: 5006
        - protocol: TCP
          port: 5007
        - protocol: TCP
          port: 4003
        - protocol: TCP
          port: 4004
        - protocol: TCP
          port: 4005
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 9042
        - protocol: TCP
          port: 9092
        - protocol: TCP
          port: 9000
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 3478
        - protocol: UDP
          port: 3478
        - protocol: TCP
          port: 4318
{{- end }}
